### PR TITLE
fix: jaas conf; make thread daemon

### LINKED ISSUE #1389: java client krb not work with  kinit
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
use keytab and principal with java client. 

2. What did you expect to see?
use keytab not fail.

4. What did you see instead?
when i use kinit ,client will auth fail.

6. What version of Pegasus are you using?
2.3.4

### PR DESCRIPTION
**Pull request by shalk**
### What problem does this PR solve? 

fix #1389 

##### Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

##### Code changes

- Has exported function/method change
- Has exported variable/fields change
- Has interface methods change
- Has persistent data change

##### Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

##### Related changes

- Need to cherry-pick to the release branch
- Need to update the documentation
- Need to be included in the release note

### CODE REVIEW

File: java-client/src/main/java/org/apache/pegasus/security/KerberosProtocol.java [hunk 1]
```diff
@@ -53,7 +54,18 @@ class KerberosProtocol implements AuthProtocol {
   private String keyTab;
   private String principal;
   final int CHECK_TGT_INTEVAL_SECONDS = 10;
-  final ScheduledExecutorService service = Executors.newSingleThreadScheduledExecutor();
+  final ScheduledExecutorService service =
+      Executors.newSingleThreadScheduledExecutor(new TgtThreadFactory());
+
+  static class TgtThreadFactory implements ThreadFactory {
```
Comment (Apache9) [inline java-client/src/main/java/org/apache/pegasus/security/KerberosProtocol.java:60]: Just create an anonymous class is enough?

File: java-client/src/main/java/org/apache/pegasus/security/KerberosProtocol.java [hunk 2]
```diff
@@ -161,19 +173,16 @@ private static Configuration getLoginContextConfiguration(String keyTab, String
       @Override
       public AppConfigurationEntry[] getAppConfigurationEntry(String name) {
         Map<String, String> options = new HashMap<>();
-        // TGT is obtained from the ticket cache.
-        options.put("useTicketCache", "true");
```
Comment (Apache9) [inline java-client/src/main/java/org/apache/pegasus/security/KerberosProtocol.java:165]: This is for keytab based login so we should remove useTicketCache, but do we support login use ticket cache? There is another method for ticker cache based login?

Comment (shalk) [reply java-client/src/main/java/org/apache/pegasus/security/KerberosProtocol.java:165]: yes, we can use ticket cache without keytab.  these can be done in the same method like hadoop

**Review by Apache9 — APPROVED** [review]

**Review by empiredan — APPROVED** [review]
